### ISSUE TITLE
pdf 中文乱码

### ISSUE THREAD

**Issue by BabelQwerty** [doscriptsite/ZSXQ-Spider#1]
pdf 中文乱码。
![image](https://user-images.githubusercontent.com/107346740/217134176-5ef0fec0-50ba-422e-9583-f085d248a0da.png)

**Comment by doscriptsite** [comment]
是任务中所有的pdf都乱码么？

造成这个问题的原因有几个：
1. wkhtmltopdf版本问题；
2. 执行导出PDF是经过命令行通道，会被环境变量所影响；
3. 个别zsxq页面有无效字符，导致抓取后的编码错误；

**Comment by BabelQwerty** [comment]
> 是任务中所有的pdf都乱码么？
> 
> 造成这个问题的原因有几个：
> 
> 1. wkhtmltopdf版本问题；
> 2. 执行导出PDF是经过命令行通道，会被环境变量所影响；
> 3. 个别zsxq页面有无效字符，导致抓取后的编码错误；

解决了，linux没装字体。
